GET http://localhost:3000/employee HTTP/1.1

###
GET http://localhost:3000/employee/1 HTTP/1.1

###
POST http://localhost:3000/employee HTTP/1.1
Content-Type: application/json

{
    "id": 1, 
    "name": "Danica Vargas", 
    "datetime": "2024/01/20", 
    "department_id": 3, 
    "job_id": 1
}

###
PUT http://localhost:3000/employee/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Danica Vargas T.", 
    "datetime": "2024/01/20", 
    "department_id": 2, 
    "job_id": 6
}

###
DELETE http://localhost:3000/employee/1 HTTP/1.1